### ISSUE TITLE
[1.6] WSGI an PHP conflict

### ISSUE THREAD

**Issue by gnerred** [camptocamp/c2cgeoportal#1535] opened 2015-08-20 11:56 UTC
I've upgrade to 1.6.2, and now I've an error 500 with FTS. It worked well in 1.6.1. I'm not able to run step 3 of upgrade, because it checks FTS and get an error. 

Thanks

Base application : 
http://preprodnew.cartoriviera.ch/

FTS that returns an error 500 : 
http://preprodnew.cartoriviera.ch/preprod/wsgi/fulltextsearch?limit=100&partitionlimit=40&query=123&_dc=1440071418492&callback=stcCallback1001

Content of Apache log : 
[Thu Aug 20 13:50:40.738890 2015] [wsgi:error] [pid 15921] 2015-08-20 13:50:40,738 INFO  [sqlalchemy.engine.base.Engine][MainThread] SELECT anon_1.id AS anon_1_id, anon_1.label AS anon_1_label, anon_1.params AS anon_1_params, anon_1.layer_name AS anon_1_layer_name, ST_AsBinary(anon_1.the_geom) AS anon_1_the_geom 
[Thu Aug 20 13:50:40.738901 2015] [wsgi:error] [pid 15921] FROM (SELECT main.tsearch.id AS id, main.tsearch.label AS label, main.tsearch.layer_name AS layer_name, main.tsearch.role_id AS role_id, main.tsearch.public AS public, main.tsearch.ts AS ts, main.tsearch.the_geom AS the_geom, main.tsearch.params AS params, row_number() OVER (PARTITION BY main.tsearch.layer_name ORDER BY ts_rank_cd(ts, to_tsquery('french', '123:*'), 2|8) DESC, main.tsearch.label) AS row_number 
[Thu Aug 20 13:50:40.738905 2015] [wsgi:error] [pid 15921] FROM main.tsearch 
[Thu Aug 20 13:50:40.738908 2015] [wsgi:error] [pid 15921] WHERE ts @@ to_tsquery('french', '123:*') AND main.tsearch.public IS true) AS anon_1 
[Thu Aug 20 13:50:40.738911 2015] [wsgi:error] [pid 15921] WHERE anon_1.row_number <= %(row_number_1)s 
[Thu Aug 20 13:50:40.738913 2015] [wsgi:error] [pid 15921]  LIMIT %(param_1)s
[Thu Aug 20 13:50:40.739016 2015] [wsgi:error] [pid 15921] 2015-08-20 13:50:40,738 INFO  [sqlalchemy.engine.base.Engine][MainThread] {'row_number_1': 40, 'param_1': 100}
[Thu Aug 20 13:50:40.757199 2015] [wsgi:error] [pid 12806] [client 10.200.40.150:42217] Truncated or oversized response headers received from daemon process 'c2cgeoportal:preprod': /var/www/vhosts/cartoriviera_preprod/private/cartoriviera_geomapfish/apache/application.wsgi

**Comment by gnerred** [comment] 2015-08-20 12:00
@sbrunner : can I work with my application even if step 3 is not passed ?

**Comment by sbrunner** [comment] 2015-08-20 12:02
Yes :-)

**Comment by sbrunner** [comment] 2015-08-21 13:36
The cause of that is the apache module `php5` !
Uninstall it and the issue is solved...

**Comment by elemoine** [comment] 2015-08-22 12:55
https://code.google.com/p/modwsgi/wiki/ApplicationIssues mentions Apache crashes in the case of shared library conflicts. It sounds to me that we're hitting that sort of problem here. I see two options, either stop using the PHP Apache module or using a different WSGI server than Apache modwsgi for the c2cgeoportal project.

**Comment by rbovard** [comment] 2015-08-27 06:52
Same issue here.

On `1.6.2` too, with `PHP 5.6.9-0+deb8u1` enabled for customs scripts.

**Comment by gnerred** [comment] 2015-08-27 07:09
Need PHP on the server. Do I have to use it as CGI?

**Comment by sbrunner** [comment] 2015-08-27 07:41
It's a good thing to try :-)

**Comment by gnerred** [comment] 2015-08-27 12:38
Tried, now with PHP CGI, Step 3 of upgrade is now ok.

**Comment by rbovard** [comment] 2015-08-27 12:54
How did you proceed?

**Comment by gnerred** [comment] 2015-08-27 13:02
Done by C2C team infrastructure on my server : 

1. disable module apache "php5"
2. enable module apache "actions"
3. add minimal apache config one new php-cgi.conf
ScriptAlias /local-bin /usr/bin
<Directory /var/www/vhosts/www.cartoriviera.ch/htdocs/>
  AddHandler cgi-handler .php
  Action cgi-handler /local-bin/php-cgi
</Directory>

**Comment by gnerred** [comment] 2015-08-27 13:08
Now FTS works

**Comment by sbrunner** [comment] 2015-08-27 13:09
Excellent, thanks :-)

**Comment by gnerred** [comment] 2015-09-01 06:49
After having tested php script with CGI instead of Apache module, I can see that performance of execution is poor... More or less two times slower. I would prefer to work with php Apache module. Is there another solution to continue using this module ? Thanks

**Comment by yjacolin** [comment] 2015-09-09 08:23
For information and history. We installed fpm-php now in the server.

**Comment by elemoine** [comment] 2015-09-28 06:23
Can we close this?

**Closed** 2015-09-28 07:00 UTC
Labels: Workaround
