### ISSUE TITLE
Cachebust error in admin console

### ISSUE THREAD

**Issue by arnaud-morvan** [camptocamp/c2cgeoportal#1248] opened 2015-02-18 16:49 UTC
When I open layer list ( http://aprona-websig-dev.gis.internal:5000/admin/LayerV1 )
I have the following error, apparently due to cachebust / static_url on folder :
```
WebError Traceback:
⇝ IOError: [Errno 21] Is a directory: '/home/amorvan/aprona_websig/.build/venv/local/lib/python2.7/site-packages/c2cgeoportal/static/lib/openlayers/img/'
View as:   Interactive  |  Text  |  XML (full)
URL: http://aprona-websig-dev.gis.internal:5000/admin/LayerV1
Module weberror.evalexception:431 in respond         view
>>  app_iter = self.application(environ, detect_start_response)
Module fanstatic.publisher:219 in __call__         view
>>  return self.app(environ, start_response)
Module fanstatic.injector:54 in __call__         view
>>  response = request.get_response(self.app)
Module webob.request:1320 in send         view
>>  application, catch_exc_info=False)
Module webob.request:1284 in call_application         view
>>  app_iter = application(self.environ, start_response)
Module pyramid.router:243 in __call__         view
>>  response = self.invoke_subrequest(request, use_tweens=True)
Module pyramid.router:218 in invoke_subrequest         view
>>  response = handle_request(request)
Module pyramid_debugtoolbar.toolbar:166 in toolbar_tween         view
>>  return handler(request)
Module pyramid.tweens:21 in excview_tween         view
>>  response = handler(request)
Module pyramid_tm:94 in tm_tween         view
>>  reraise(*exc_info)
Module pyramid_tm:75 in tm_tween         view
>>  response = handler(request)
Module pyramid.router:164 in handle_request         view
>>  response = view_callable(context, request)
Module pyramid.config.views:600 in __call__         view
>>  return view(context, request)
Module pyramid.config.views:327 in attr_view         view
>>  return view(context, request)
Module pyramid.config.views:303 in predicate_wrapper         view
>>  return view(context, request)
Module pyramid.config.views:243 in _secured_view         view
>>  return view(context, request)
Module pyramid.config.views:353 in rendered_view         view
>>  result = view(context, request)
Module pyramid.config.views:495 in _class_view         view
>>  response = getattr(inst, attr)()
Module pyramid_formalchemy.actions:77 in wrapped         view
>>  return func(self, *args, **kwargs)
Module pyramid_formalchemy.views:312 in listing         view
>>  zope.component.event.objectEventNotify(event)
Module zope.component.event:36 in objectEventNotify         view
>>  component_subscribers((event.object, event), None)
Module zope.component._api:139 in subscribers         view
>>  return sitemanager.subscribers(objects, interface)
Module zope.interface.registry:328 in subscribers         view
>>  return self.adapters.subscribers(objects, provided)
Module zope.interface.adapter:600 in subscribers         view
>>  subscription(*objects)
Module c2cgeoportal.forms:123 in before_render_layer         view
>>  get_fanstatic_resources(event.request).need()
Module c2cgeoportal.forms:96 in get_fanstatic_resources         view
>>  olimgpath = request.static_url('c2cgeoportal:static/lib/openlayers/img/')
Module pyramid.url:717 in static_url         view
>>  return info.generate(path, self, **kw)
Module c2cgeoportal.lib:130 in generate         view
>>  subpath, kw = cachebust(subpath, kw)
Module pyramid.config.views:1985 in cachebust         view
>>  spec + subpath, subpath_tuple, kw)
Module pyramid.static:206 in pregenerate         view
>>  token = self.tokenize(pathspec)
Module pyramid.static:192 in tokenize         view
>>  self.token_cache[pathspec] = token = _generate_md5(pathspec)
Module pyramid.static:163 in _generate_md5         view
>>  with asset.stream() as stream:
Module pyramid.path:402 in stream         view
>>  return self.pkg_resources.resource_stream(self.pkg_name, self.path)
Module pkg_resources:1135 in resource_stream         view
>>  self, resource_name
Module pkg_resources:1689 in get_resource_stream         view
>>  return open(self._fn(self.module_path, resource_name), 'rb')
IOError: [Errno 21] Is a directory: '/home/amorvan/aprona_websig/.build/venv/local/lib/python2.7/site-packages/c2cgeoportal/static/lib/openlayers/img/'
Extra Features
>>	Display the lines of code near each part of the traceback
	Show a debug prompt to allow you to directly debug the code at the traceback

**Comment by sbrunner** [comment] 2015-02-24 18:53
Unable to reproduce, probably related on one of the today merged pull requests, I just push the update commits in the data branch of the project.

**Closed by sbrunner** 2015-02-24 18:53 UTC
Labels: TODO
