### ISSUE TITLE
Upgrade from 1.6.8 to 2.1.0.dev14 error pkg_resources.DistributionNotFound

### ISSUE THREAD

**Issue by svavoi** [camptocamp/c2cgeoportal#2482] opened 2016-09-02 12:22 UTC
After following all the steps in the changelog.diff for Version 2.0.0 and 2.1.0 I tried to build the application, but I get the following python error:
```
svavoi@bvdgdi-svdmbap2:~/mapbs$ make -f svavoi.mk build
DEST_DB= DEST_DBHOST= .build/venv/bin/c2c-template --vars ../vars_secure.yaml --engine mako --files jsbuild/app.cfg.mako
Traceback (most recent call last):
  File ".build/venv/bin/c2c-template", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/home/svavoi/mapbs/.build/venv/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 2707, in <module>
    working_set.require(__requires__)
  File "/home/svavoi/mapbs/.build/venv/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 686, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/svavoi/mapbs/.build/venv/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: six
make: *** [jsbuild/app.cfg] Error 1
```

What can I try to do?

**Comment by sbrunner** [comment] 2016-09-02 12:45
You don't finish the upgrade process with c2ctool?

**Comment by svavoi** [comment] 2016-09-02 12:49
What would the command be for it?
I tried to build it, to be able to run the migrate script `.build/venv/bin/themev1tov2`...

**Comment by sbrunner** [comment] 2016-09-02 13:20
Effectively I'm not clear, di you finish the upgrade steps?
`make -f <...> upgade<1-6>`

**Comment by svavoi** [comment] 2016-09-02 13:31
No I did not.

**Comment by svavoi** [comment] 2016-09-02 13:35
Running the first step `make -f svavoi.mk upgrade 1` I get the same error again.

```
DEST_DB= DEST_DBHOST= .build/venv/bin/c2c-template --vars ../vars_secure.yaml --engine mako --files project.yaml.mako
Traceback (most recent call last):
  File ".build/venv/bin/c2c-template", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/home/svavoi/mapbs/.build/venv/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 2707, in <module>
    working_set.require(__requires__)
  File "/home/svavoi/mapbs/.build/venv/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 686, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/svavoi/mapbs/.build/venv/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: six
make: *** [project.yaml] Error 1
```

**Comment by sbrunner** [comment] 2016-09-02 14:10
I never try to do a migration from version 1.6 to 2.1, I think that safer to pass by the version `2.0.0rc6`...

If you want to continue can you commit your changes in a branch to allow to see and test?

**Comment by svavoi** [comment] 2016-09-02 14:30
I just committed by changed on this branch:
https://github.com/camptocamp/baselstadt_mapbs/tree/GMF2_1_Beta
If you think it's safer to pass from version 2.0.0 I will start all over again on Monday.

**Comment by sbrunner** [comment] 2016-09-02 15:23
I don't have this specific error, can you try to do a `cleanall`?

**Comment by svavoi** [comment] 2016-09-05 09:37
I run a `cleanall` and tried again with the build but I still get the same error.
What I also get are some warnings. Not sure if this is related to the error though ...
```
/home/svavoi/mapbs/.build/venv/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: 
A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. 
You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
InsecurePlatformWarning
```
and those two if I run the first step `make -f svavoi.mk upgrade 1`:
```
npm WARN mapbs@2.0.0 No repository field.
npm WARN mapbs@2.0.0 No license field.
```

**Comment by svavoi** [comment] 2016-09-05 11:35
Or is it a problem, that we are not yet on the newest GeoMapFish puppet installer? At the moment we are still using 0.14.2 with Debian Wheezy (because we can not update to Jessy due to infrastructure conflicts).

**Comment by eleu** [comment] 2016-09-06 16:00
This error is due to missing middleware requirements. Closing the issue because the cause lies in the middleware.

**Closed by eleu** 2016-09-06 16:00 UTC
Labels: Infrastructure, Ready
